### ISSUE TITLE
Determine standard for variables that need replacing/updating

### ISSUE THREAD

**Issue by nixwiz** [sensu-community/catalog#27]
For items that would need to be replaced for a resource to work, we should have a standard naming convention.

Possibles:
REPLACEME_DESCRIPTION
CHANGEME_DESCRIPTION
UPDATE_DESCRIPTION

For items that have a standard value (such as port numbers), we should use those instead of a reference.  Doing a `sensuctl create` on the below would error out because spec.socket.port is expected to be an integer.

```
---
type: Handler
api_version: core/v2
metadata:
  name: graphite_tcp
  namespace: default
spec:
  env_vars: []
  filters: []
  handlers: []
  mutator: only_check_output
  runtime_assets: []
  secrets:
  socket:
    host: REPLACEME_GRAPHITE_HOST
    port: REPLACEME_GRAPHITE_PORT
  timeout: 0
  type: tcp
```

Should we also consider using localhost for any host or URL defaults?
